server:
  port: 8761
spring:
  application:
    name: registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://imooc:123456@localhost:${server.port}/eureka
security:
  basic:
    enabled: false
  user:
    name: imooc
    password: 123456
