server:
  port: 8888
spring:
  application:
    name: proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://imooc:123456@localhost:8761/eureka
zuul:
  routes:
    userApi:
      path: /home/**
      serviceId: user
      stripPrefix: false